# docker version
version: "3.8"
services:
  nba-client:
    # image
    build:
      context: ./client
      dockerfile: Dockerfile
    # container
    container_name: client-dc
    ports:
      - 3000:3000
      # - array, can be multiples
    volumes:
      - './client:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
  nba-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-dc
    ports:
      - 5000:5000
    volumes:
      - './server:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    # not actual needed


      

# spacing is very important.